version: "3"

tasks:
  fetch_articles:
    cmds:
      - rm -f article-prompt.md ERROR.md
      - uv run create_article_prompt.py --date {{ default (now | date "2006-01-02") .DATE }} > article-prompt.md
      - |
        cat article-prompt.md | claude -p \
          --allowedTools "WebSearch,WebFetch,Read,Bash,Write" \
          --model sonnet
      - test ! -f ERROR.md

  serve:
    cmds:
      - npx @11ty/eleventy --serve
