version: "3"

tasks:
  fetch_articles:
    cmds:
      - rm -f article-prompt.md ERROR.md
      - uv run create_article_prompt.py {{if .DATE}}--date {{.DATE}}{{end}} > article-prompt.md
      - cat article-prompt.md | claude -p --model sonnet
      - test ! -f ERROR.md

  serve:
    cmds:
      - npx @11ty/eleventy --serve
